import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    expenses: "Expenses",
    settings: "Settings",
    
    // Auth
    signIn: "Sign In",
    signUp: "Sign Up",
    email: "Email",
    password: "Password",
    username: "Username (optional)",
    signOut: "Sign Out",
    tryDemo: "Try Demo",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    signInToAccess: "Sign in to access your budget data",
    signUpToSave: "Sign up to save your budget data",
    signingIn: "Signing in...",
    creatingAccount: "Creating account...",
    noAccountRequired: "No Account Required",
    demoModeSaves: "Demo mode saves data locally on your device",
    trackExpensesManage: "Track your expenses and manage your budget",
    iAgreeToThe: "I agree to the",
    termsAndConditions: "Terms and Conditions",
    
    // Dashboard
    spendingPower: "Spending Power",
    accounts: "Accounts",
    budgetSettings: "Budget Settings",
    monthlyBudget: "Monthly Budget",
    salaryDate: "Salary Date",
    save: "Save",
    totalSpendable: "Total Spendable",
    fromActiveAccounts: "From active accounts",
    currentCycle: "Current Cycle",
    daysLeft: "Days left",
    spentThisCycle: "Spent this cycle",
    remainingThisCycle: "Remaining this cycle",
    overBudgetThisCycle: "Over budget this cycle",
    exceededBudgetBy: "You've exceeded your monthly budget by",
    recommendedDailySpend: "Recommended daily spend",
    spentToday: "Spent today",
    totalSpent: "Total Spent",
    netSavings: "Net Savings",
    
    // Transactions
    addTransaction: "Add Transaction",
    amount: "Amount",
    description: "Description",
    category: "Category",
    date: "Date",
    pasteTransaction: "Paste Bank Transaction (AI)",
    parseWithAI: "Parse with AI",
    cancel: "Cancel",
    recentTransactions: "Recent Transactions",
    noTransactions: "No transactions yet",
    startTracking: "Start tracking your expenses to see them here",
    type: "Type",
    expense: "Expense",
    income: "Income",
    newTransaction: "New Transaction",
    pasteTransactionText: "Paste Transaction Text",
    pasteYourBank: "Paste your bank transaction text here...",
    parsing: "Parsing...",
    selectCategory: "Select category",
    paymentMethod: "Payment Method",
    selectPaymentMethod: "Select payment method",
    descriptionOptional: "Description (Optional)",
    addNotes: "Add notes...",
    thisCycleTransactions: "This Cycle's Transactions",
    noTransactionsCycle: "No transactions this cycle",
    payment: "Payment",
    creditCard: "Credit Card",
    currentAccount: "Current Account",
    savingsAccount: "Savings Account",
    cash: "Cash",
    emergencyFund: "Emergency Fund",
    transactionAdded: "Transaction added successfully!",
    transactionDeleted: "Transaction Deleted",
    transactionRemoved: "The transaction has been removed successfully",
    pleasePasteText: "Please paste transaction text",
    failedToParse: "Failed to parse transaction",
    transactionParsed: "Transaction parsed! Review and submit.",
    pleaseFillRequired: "Please fill in all required fields",
    pasteBankSMSTooltip: "Paste Bank SMS to extract transaction",
    
    // Categories
    food: "Food",
    transport: "Transport",
    shopping: "Shopping",
    bills: "Bills",
    entertainment: "Entertainment",
    health: "Health",
    other: "Other",
    
    // Settings
    languageSettings: "Language Settings",
    selectLanguage: "Select Language",
    english: "English",
    arabic: "Arabic",
    accountSettings: "Account Settings",
    userId: "User ID",
    accountName: "Account Name",
    balance: "Balance",
    includeInTotal: "Include in Total Spendable",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    spendable: "Spendable",
    name: "Name",
    saveBudgetSettings: "Save Budget Settings",
    setSpendingLimit: "Set your spending limit for each cycle",
    salaryDepositDate: "Salary Deposit Date (1-31)",
    spendingCycleRuns: "Your spending cycle runs from the",
    toThe: "to the",
    ofEachMonth: "of each month",
    th: "th",
    
    // Landing Page
    takeControlFinances: "Take Control of Your Finances",
    fastestIntuitive: "The fastest, most intuitive way to track spending and stay on budget. Designed for people who value their time and money.",
    newUser: "New User",
    startTrackingFinances: "Start tracking your finances today",
    existingUser: "Existing User",
    welcomeBackSignIn: "Welcome back! Sign in to continue",
    lightningFastEntry: "Lightning Fast Entry",
    logTransactions: "Log transactions in under 10 seconds",
    smartInsights: "Smart Insights",
    realtimeSpending: "Real-time spending analysis and alerts",
    securePrivate: "Secure & Private",
    dataStaysProtected: "Your financial data stays protected",
    everythingYouNeed: "Everything you need to manage money",
    getStartedNow: "Get Started Now",
    trackIncomeExpenses: "Track income and expenses effortlessly",
    manageMultipleAccounts: "Manage multiple accounts and payment methods",
    customMonthlyCycles: "Custom monthly cycles (20th-19th)",
    smartSpendingAlerts: "Smart spending alerts and daily budgets",
    simplePayment: "Simple one-time payment",
    copyright: "Take control of your finances.",
    
    // Common
    getStarted: "Get Started",
    trackEveryDinar: "Track every dinar",
    kwd: "KWD",
    day: "day",
    invalidInput: "Invalid input",
    accountUpdated: "Account updated",
    accountDeleted: "Account deleted",
    accountAdded: "Account added",
    pleaseEnterValid: "Please enter a valid name and positive balance",
    accountDetailsSaved: "Account details have been saved",
    accountRemoved: "Account has been removed",
    newAccountCreated: "New account has been created",
    invalidBudget: "Invalid Budget",
    pleaseEnterValidBudget: "Please enter a valid monthly budget",
    invalidDate: "Invalid Date",
    salaryDateBetween: "Salary date must be between 1 and 31",
    budgetSettingsSaved: "Budget Settings Saved",
    monthlyBudgetUpdated: "Your monthly budget has been updated",
    myAccount: "My Account",
    
    // Fixed & One-Time Expenses
    fixedExpenses: "Fixed Expenses",
    oneTimeExpenses: "One-Time Expenses",
    addFixedExpense: "Add Fixed Expense",
    addOneTimeExpense: "Add One-Time Expense",
    totalMonthlyCommitments: "Total Monthly Commitments",
    totalOneTimeCommitments: "Total One-Time Commitments",
    remainingNotPaid: "Remaining (Not Paid)",
    netSpendableAfterCommitments: "Net Spendable After Commitments",
    spendableMinusCommitments: "Spendable – Remaining Fixed – Remaining One-Time",
    resetAllToNotPaid: "Reset All to Not Paid",
    resetConfirmTitle: "Reset All Expenses?",
    resetConfirmDescription: "This will mark all expenses as Not Paid. This action cannot be undone.",
    allExpensesReset: "All Expenses Reset",
    allExpensesMarkedUnpaid: "All expenses have been marked as not paid",
    expenseAdded: "Expense Added",
    expenseAddedSuccess: "The expense has been added successfully",
    expenseUpdated: "Expense Updated",
    expenseUpdatedSuccess: "The expense has been updated successfully",
    expenseDeleted: "Expense Deleted",
    expenseDeletedSuccess: "The expense has been deleted successfully",
    confirmDelete: "Confirm Delete",
    confirmDeleteDescription: "Are you sure you want to delete this expense? This action cannot be undone.",
    editExpense: "Edit Expense",
    paid: "Paid",
    notPaid: "Not Paid",
    markAsPaid: "Mark as Paid",
    markAsNotPaid: "Mark as Not Paid",
    noExpensesYet: "No expenses yet",
    startAddingExpenses: "Start adding expenses to track your commitments",
    search: "Search",
    searchExpenses: "Search expenses...",
  },
  ar: {
    // Navigation
    dashboard: "لوحة التحكم",
    expenses: "المصروفات",
    settings: "الإعدادات",
    
    // Auth
    signIn: "تسجيل الدخول",
    signUp: "إنشاء حساب",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    username: "اسم المستخدم (اختياري)",
    signOut: "تسجيل الخروج",
    tryDemo: "تجربة العرض التوضيحي",
    welcomeBack: "مرحبًا بعودتك",
    createAccount: "إنشاء حساب",
    signInToAccess: "سجل الدخول للوصول إلى بيانات ميزانيتك",
    signUpToSave: "سجل لحفظ بيانات ميزانيتك",
    signingIn: "جارٍ تسجيل الدخول...",
    creatingAccount: "جارٍ إنشاء الحساب...",
    noAccountRequired: "لا يلزم حساب",
    demoModeSaves: "الوضع التجريبي يحفظ البيانات محليًا على جهازك",
    trackExpensesManage: "تتبع نفقاتك وأدر ميزانيتك",
    iAgreeToThe: "أوافق على",
    termsAndConditions: "الشروط والأحكام",
    
    // Dashboard
    spendingPower: "القوة الشرائية",
    accounts: "الحسابات",
    budgetSettings: "إعدادات الميزانية",
    monthlyBudget: "الميزانية الشهرية",
    salaryDate: "تاريخ الراتب",
    save: "حفظ",
    totalSpendable: "إجمالي المبالغ القابلة للصرف",
    fromActiveAccounts: "من الحسابات النشطة",
    currentCycle: "الدورة الحالية",
    daysLeft: "الأيام المتبقية",
    spentThisCycle: "المصروف في هذه الدورة",
    remainingThisCycle: "المتبقي في هذه الدورة",
    overBudgetThisCycle: "تجاوزت الميزانية في هذه الدورة",
    exceededBudgetBy: "لقد تجاوزت ميزانيتك الشهرية بمقدار",
    recommendedDailySpend: "الإنفاق اليومي الموصى به",
    spentToday: "المصروف اليوم",
    totalSpent: "إجمالي المصروفات",
    netSavings: "صافي المدخرات",
    
    // Transactions
    addTransaction: "إضافة معاملة",
    amount: "المبلغ",
    description: "الوصف",
    category: "الفئة",
    date: "التاريخ",
    pasteTransaction: "لصق معاملة من البنك (ذكاء اصطناعي)",
    parseWithAI: "تحليل بالذكاء الاصطناعي",
    cancel: "إلغاء",
    recentTransactions: "المعاملات الأخيرة",
    noTransactions: "لا توجد معاملات بعد",
    startTracking: "ابدأ بتتبع نفقاتك لرؤيتها هنا",
    type: "النوع",
    expense: "مصروف",
    income: "دخل",
    newTransaction: "معاملة جديدة",
    pasteTransactionText: "لصق نص المعاملة",
    pasteYourBank: "الصق نص معاملتك البنكية هنا...",
    parsing: "جارٍ التحليل...",
    selectCategory: "اختر الفئة",
    paymentMethod: "طريقة الدفع",
    selectPaymentMethod: "اختر طريقة الدفع",
    descriptionOptional: "الوصف (اختياري)",
    addNotes: "أضف ملاحظات...",
    thisCycleTransactions: "معاملات هذه الدورة",
    noTransactionsCycle: "لا توجد معاملات في هذه الدورة",
    payment: "الدفع",
    creditCard: "بطاقة ائتمانية",
    currentAccount: "حساب جاري",
    savingsAccount: "حساب توفير",
    cash: "نقدًا",
    emergencyFund: "صندوق الطوارئ",
    transactionAdded: "تمت إضافة المعاملة بنجاح!",
    transactionDeleted: "تم حذف المعاملة",
    transactionRemoved: "تم إزالة المعاملة بنجاح",
    pleasePasteText: "يرجى لصق نص المعاملة",
    failedToParse: "فشل تحليل المعاملة",
    transactionParsed: "تم التحليل! راجع واحفظ.",
    pleaseFillRequired: "يرجى ملء جميع الحقول المطلوبة",
    pasteBankSMSTooltip: "الصق رسالة البنك لاستخراج المعلومات",
    
    // Categories
    food: "طعام",
    transport: "مواصلات",
    shopping: "تسوق",
    bills: "فواتير",
    entertainment: "ترفيه",
    health: "صحة",
    other: "أخرى",
    
    // Settings
    languageSettings: "إعدادات اللغة",
    selectLanguage: "اختر اللغة",
    english: "الإنجليزية",
    arabic: "العربية",
    accountSettings: "إعدادات الحساب",
    userId: "معرف المستخدم",
    accountName: "اسم الحساب",
    balance: "الرصيد",
    includeInTotal: "إضافة إلى الإجمالي القابل للصرف",
    add: "إضافة",
    edit: "تعديل",
    delete: "حذف",
    spendable: "قابل للصرف",
    name: "الاسم",
    saveBudgetSettings: "حفظ إعدادات الميزانية",
    setSpendingLimit: "حدد حد الإنفاق الخاص بك لكل دورة",
    salaryDepositDate: "تاريخ إيداع الراتب (1-31)",
    spendingCycleRuns: "تبدأ دورة الإنفاق من اليوم",
    toThe: "إلى",
    ofEachMonth: "من كل شهر",
    th: "",
    
    // Landing Page
    takeControlFinances: "سيطر على أموالك",
    fastestIntuitive: "الطريقة الأسرع والأكثر سهولة لتتبع الإنفاق والالتزام بالميزانية. مصمم للأشخاص الذين يقدرون وقتهم وأموالهم.",
    newUser: "مستخدم جديد",
    startTrackingFinances: "ابدأ بتتبع أموالك اليوم",
    existingUser: "مستخدم حالي",
    welcomeBackSignIn: "مرحبًا بعودتك! سجل الدخول للمتابعة",
    lightningFastEntry: "إدخال سريع جدًا",
    logTransactions: "سجل المعاملات في أقل من 10 ثوانٍ",
    smartInsights: "رؤى ذكية",
    realtimeSpending: "تحليل الإنفاق في الوقت الفعلي والتنبيهات",
    securePrivate: "آمن وخاص",
    dataStaysProtected: "بياناتك المالية محمية",
    everythingYouNeed: "كل ما تحتاجه لإدارة الأموال",
    getStartedNow: "ابدأ الآن",
    trackIncomeExpenses: "تتبع الدخل والمصروفات بسهولة",
    manageMultipleAccounts: "إدارة حسابات متعددة وطرق دفع",
    customMonthlyCycles: "دورات شهرية مخصصة (من 20 إلى 19)",
    smartSpendingAlerts: "تنبيهات إنفاق ذكية وميزانيات يومية",
    simplePayment: "دفعة واحدة بسيطة",
    copyright: "سيطر على أموالك.",
    
    // Common
    getStarted: "ابدأ الآن",
    trackEveryDinar: "تتبع كل دينار",
    kwd: "د.ك",
    day: "يوم",
    invalidInput: "إدخال غير صحيح",
    accountUpdated: "تم تحديث الحساب",
    accountDeleted: "تم حذف الحساب",
    accountAdded: "تمت إضافة الحساب",
    pleaseEnterValid: "يرجى إدخال اسم صحيح ورصيد موجب",
    accountDetailsSaved: "تم حفظ تفاصيل الحساب",
    accountRemoved: "تم إزالة الحساب",
    newAccountCreated: "تم إنشاء حساب جديد",
    invalidBudget: "ميزانية غير صحيحة",
    pleaseEnterValidBudget: "يرجى إدخال ميزانية شهرية صحيحة",
    invalidDate: "تاريخ غير صحيح",
    salaryDateBetween: "يجب أن يكون تاريخ الراتب بين 1 و 31",
    budgetSettingsSaved: "تم حفظ إعدادات الميزانية",
    monthlyBudgetUpdated: "تم تحديث ميزانيتك الشهرية",
    myAccount: "حسابي",
    
    // Fixed & One-Time Expenses
    fixedExpenses: "المصروفات الثابتة",
    oneTimeExpenses: "المصروفات لمرة واحدة",
    addFixedExpense: "إضافة مصروف ثابت",
    addOneTimeExpense: "إضافة مصروف لمرة واحدة",
    totalMonthlyCommitments: "إجمالي الالتزامات الشهرية",
    totalOneTimeCommitments: "إجمالي الالتزامات لمرة واحدة",
    remainingNotPaid: "المتبقي (غير مدفوع)",
    netSpendableAfterCommitments: "صافي المبلغ القابل للصرف بعد الالتزامات",
    spendableMinusCommitments: "القابل للصرف – الثابت المتبقي – لمرة واحدة المتبقي",
    resetAllToNotPaid: "إعادة تعيين الكل كغير مدفوع",
    resetConfirmTitle: "إعادة تعيين جميع المصروفات؟",
    resetConfirmDescription: "سيتم تعليم جميع المصروفات كغير مدفوعة. لا يمكن التراجع عن هذا الإجراء.",
    allExpensesReset: "تمت إعادة تعيين جميع المصروفات",
    allExpensesMarkedUnpaid: "تم تعليم جميع المصروفات كغير مدفوعة",
    expenseAdded: "تمت إضافة المصروف",
    expenseAddedSuccess: "تمت إضافة المصروف بنجاح",
    expenseUpdated: "تم تحديث المصروف",
    expenseUpdatedSuccess: "تم تحديث المصروف بنجاح",
    expenseDeleted: "تم حذف المصروف",
    expenseDeletedSuccess: "تم حذف المصروف بنجاح",
    confirmDelete: "تأكيد الحذف",
    confirmDeleteDescription: "هل أنت متأكد من رغبتك في حذف هذا المصروف؟ لا يمكن التراجع عن هذا الإجراء.",
    editExpense: "تعديل المصروف",
    paid: "مدفوع",
    notPaid: "غير مدفوع",
    markAsPaid: "تعليم كمدفوع",
    markAsNotPaid: "تعليم كغير مدفوع",
    noExpensesYet: "لا توجد مصروفات بعد",
    startAddingExpenses: "ابدأ بإضافة المصروفات لتتبع التزاماتك",
    search: "بحث",
    searchExpenses: "البحث عن المصروفات...",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
