export const TERMS_AND_CONDITIONS = {
  en: {
    title: "Terms and Conditions",
    content: `Welcome to EzKash ("the App"). By creating an account, signing in, or using the App, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions ("Terms").

**1. Purpose of the App**

EzKash is a personal finance tracking tool that allows users to record and monitor their own income, expenses, and commitments. The App is provided for personal informational purposes only and does not provide financial, investment, or accounting advice.

**2. User Responsibility**

You agree that:

- All information you enter into the App (transactions, budgets, income, expenses, or otherwise) is your sole responsibility.
- EzKash does not verify the accuracy, completeness, or reliability of any data you provide.
- Any calculations, reports, summaries, or insights generated by the App are based on the data you input, and may contain errors or inaccuracies.
- You are solely responsible for all decisions made using or based on information from the App.

**3. Disclaimer of Warranties**

The App is provided "as is" and "as available." EzKash and its owners, developers, and affiliates make no warranties of any kind, express or implied, including but not limited to:

- Accuracy or reliability of any information displayed in the App,
- Availability or uninterrupted access,
- Freedom from viruses, bugs, or unauthorized access,
- Compliance with specific financial or accounting standards.

**4. Limitation of Liability**

EzKash and its owners shall not be liable for any direct, indirect, incidental, consequential, or special damages arising from the use or inability to use the App.

This includes, without limitation, loss of data, financial loss, loss of profits, reputational harm, or any other damages—even if the possibility of such damages was known.

In no event shall EzKash's total liability exceed the amount you paid for the App (if any).

**5. Data & Privacy**

The App stores data either locally on your device or, if cloud synchronization is enabled, on secure third-party servers.

While reasonable measures are taken to protect your data, EzKash cannot guarantee absolute security.

By using the App, you acknowledge that you assume responsibility for managing and protecting your own data.

EzKash will not be responsible for any data compromise, including those resulting from hacking, device loss, or misuse.

**6. User Accounts & Access**

You are responsible for maintaining the confidentiality of your username and password.

You must notify EzKash immediately of any unauthorized use of your account.

EzKash reserves the right to suspend or terminate accounts that violate these Terms, engage in suspicious activity, or misuse the App.

**7. Data Accuracy & External Inputs**

Any imported data (e.g., via CSV files, SMS parsing, or bank notifications) is processed automatically.

EzKash does not guarantee that such information is interpreted correctly.

**8. Subscription, Fees, and Refunds**

If EzKash is offered as a paid app or subscription, all purchases are final and non-refundable.

EzKash may update pricing or introduce new features at any time.

Free trials are provided solely for evaluation purposes and may be changed or withdrawn without notice.

**9. Intellectual Property**

All intellectual property rights in the App, including software, design, text, graphics, and logos, are owned by EzKash or its licensors. You may not reproduce, distribute, or modify any part of the App without prior written consent.

**10. Termination of Use**

EzKash reserves the right to:

- Modify, suspend, or discontinue any part of the App at any time,
- Terminate or restrict user access without notice,
- Delete user data if required by law or upon account deletion.

**11. No Guarantee of Continuous Service**

EzKash is not obligated to maintain or continue operation of the App or its servers. Service interruptions, updates, or discontinuation may occur without notice or liability.

**12. Acceptance**

By clicking "I Agree" or using the App, you confirm that:

- You have read and understood these Terms,
- You voluntarily accept all responsibility related to the use of EzKash.`
  },
  ar: {
    title: "الشروط والأحكام – تطبيق EzKash",
    content: `مرحباً بك في تطبيق EzKash ("التطبيق"). باستخدامك للتطبيق أو بإنشائك حساباً جديداً، فإنك تقر بأنك قد قرأت وفهمت ووافقت على الالتزام بهذه الشروط والأحكام.

**هدف التطبيق**

يعد EzKash أداة لتتبع النفقات الشخصية تتيح للمستخدم تسجيل ومتابعة الدخل والمصاريف والالتزامات الخاصة به.

يقدم التطبيق لأغراض شخصية فقط، ولا يعتبر نصيحة مالية أو استثمارية أو محاسبية.

**مسؤولية المستخدم**

تقع ضمن مسؤوليته الكاملة جميع البيانات التي يقوم المستخدم بإدخالها (المعاملات، الميزانيات، الدخل، المصاريف، وغيرها).

لا يتحقق EzKash من دقة أو اكتمال أو صحة البيانات التي يقدمها المستخدم.

**إخلاء المسؤولية عن الضمانات**

يتحمل المستخدم وحده مسؤولية جميع القرارات المالية التي يتخذها بناءً على المعلومات المعروضة في التطبيق.

أي تقارير أو ملخصات أو تحليلات يصدرها التطبيق تعتمد على البيانات التي يدخلها المستخدم وقد تحتوي على أخطاء.

**تحديد المسؤولية**

يقدم التطبيق "كما هو" و "حسب توفره". ولا يقدم EzKash أو مطوروه أو شركاؤه أي ضمانات صريحة أو ضمنية من أي نوع، بما في ذلك على سبيل المثال لا الحصر:

دقة المعلومات أو موثوقيتها، توفر الخدمة أو استمراريتها دون انقطاع، خلو التطبيق من الأخطاء أو محاولات الوصول غير المصرح بها. توافقه مع أي معايير مالية أو محاسبية محددة.

لا يتحمل EzKash أو أصحابه أي مسؤولية عن أي أضرار مباشرة أو غير مباشرة أو تبعية أو خاصة ناتجة عن استخدام التطبيق أو عدم القدرة على استخدامه.

يشمل ذلك – دون حصر – فقدان البيانات أو الخسائر المالية أو الأرباح أو السمعة.

في جميع الحالات، لا تتجاوز مسؤولية EzKash الإجمالية المبلغ الذي دفعه المستخدم مقابل التطبيق (إن وجد).

**5. البيانات والخصوصية**

يتم تخزين البيانات إما محلياً على جهاز المستخدم – أو في حال تفعيل المزامنة السحابية – على خوادم طرف ثالث آمنة.

رغم اتخاذ تدابير لحماية البيانات، لا يمكن لـ EzKash ضمان الأمان المطلق.

يتحمل المستخدم مسؤولية إدارة بياناته وحمايتها.

لا يتحمل EzKash أي مسؤولية عن أي اختراق أو فقدان للبيانات أو إساءة استخدام لها، بما في ذلك الحوادث الناتجة عن القرصنة أو فقدان الجهاز.

**6. حساب المستخدم والوصول إليه**

يتحمل المستخدم مسؤولية الحفاظ على سرية اسم المستخدم وكلمة المرور الخاصة به.

يجب على المستخدم إخطار EzKash فوراً في حال حدوث أي استخدام غير مصرح به للحساب.

يحق لـ EzKash تعليق أو إيقاف الحسابات التي تنتهك الشروط أو تستخدم التطبيق بطريقة غير مشروعة.

**7. دقة البيانات والمدخلات الخارجية**

أي بيانات يتم استيرادها (مثل ملفات CSV أو الرسائل البنكية) يتم معالجتها آلياً.

لا يضمن EzKash تفسير هذه البيانات بدقة تامة.

يجب على المستخدم مراجعة جميع المدخلات قبل الاعتماد عليها في اتخاذ قرارات مالية.

**8. الاشتراكات والرسوم والاسترجاع**

في حال كان التطبيق مدفوعاً أو يعتمد على اشتراك، فإن جميع المشتريات نهائية ولا يمكن استردادها.

يحق لـ EzKash تعديل الأسعار أو إضافة ميزات جديدة في أي وقت دون إشعار مسبق.

تستخدم الفترة التجريبية المجانية لغرض التجربة فقط ويمكن تعديلها أو إلغاؤها دون إشعار.

**9. الملكية الفكرية**

جميع حقوق الملكية الفكرية الخاصة بالتطبيق بما في ذلك التصميم والبرمجة والنصوص والرسومات والشعارات تعود لـ EzKash أو للجهات المرخصة له.

لا يسمح بنسخ أو توزيع أو تعديل أي جزء من التطبيق دون موافقة كتابية مسبقة.

**10. إنهاء الاستخدام**

يحتفظ EzKash بالحق في:

تعديل أو تعليق أو إيقاف أي جزء من التطبيق في أي وقت، إنهاء أو تقييد وصول المستخدم دون إشعار مسبق. حذف بيانات المستخدم إذا تطلب القانون ذلك أو عند إغلاق الحساب.

**11. عدم ضمان استمرار الخدمة**

لا يلتزم EzKash بالحفاظ على تشغيل التطبيق أو خوادمه بشكل دائم. قد تحدث انقطاعات أو تحديثات أو توقفات في الخدمة دون إشعار مسبق أو التزام بالتعويض.

**12. القبول**

بالضغط على "أوافق" أو باستخدام التطبيق، فإنك تؤكد أنك قد قرأت هذه الشروط وفهمتها. وأنك تقبل طوعاً جميع المسؤوليات المتعلقة باستخدام تطبيق EzKash.`
  }
};
